In [9]:
import pandas as pd
from slugify import slugify
import json

In [2]:
data = pd.read_excel('/home/abhinav/sink/D4D/Master_file_mgnrega.xlsx', engine='openpyxl')

/home/abhinav/pyprojenv/lib/python3.6/site-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

In [3]:
data['district_name'] = data['district_name'].map(lambda x: x.title())
data['block_name'] = data['block_name'].map(lambda x: x.title())

In [4]:
def f(x):
    d = {}
    d['cesaf'] = round(100 * (x[x['indicator_slug'] == 'tcexp']['indicator_value'].sum() / x[x['indicator_slug'] == 'tavlf']['indicator_value'].sum()), 2)
    d['pdcpd'] = round(100 * (x[x['indicator_slug'] == 'npdgn']['indicator_value'].sum() / x[x['indicator_slug'] == 'cpmar']['indicator_value'].sum()), 2)
    d['aeaaw'] = round(100 * (x[x['indicator_slug'] == 'nobaw']['indicator_value'].sum() / x[x['indicator_slug'] == 'notww']['indicator_value'].sum()), 2)
    d['ppcgt'] = round(100 * (x[x['indicator_slug'] == 'nwgs3']['indicator_value'].sum() / x[x['indicator_slug'] == 'tnws3']['indicator_value'].sum()), 2)

    d['sscjc'] = round(100 * (x[x['indicator_slug'] == 'nscjc']['indicator_value'].sum() / x[x['indicator_slug'] == 'notww']['indicator_value'].sum()), 2)
    d['sstjc'] = round(100 * (x[x['indicator_slug'] == 'nstjc']['indicator_value'].sum() / x[x['indicator_slug'] == 'notww']['indicator_value'].sum()), 2)
    d['sonsn'] = round(100 * (x[x['indicator_slug'] == 'nonsn']['indicator_value'].sum() / x[x['indicator_slug'] == 'notww']['indicator_value'].sum()), 2)
    d['stwac'] = round(100 * (x[x['indicator_slug'] == 'ntwacss']['indicator_value'].sum() / x[x['indicator_slug'] == 'notww']['indicator_value'].sum()), 2)   

    d['easeo'] = round(100 * (x[x['indicator_slug'] == 'nopwa']['indicator_value'].sum() / x[x['indicator_slug'] == 'nopoe']['indicator_value'].sum()), 2)
    d['ntdm8'] = round((x[x['indicator_slug'] == 'dpt15']['indicator_value'].sum() + x[x['indicator_slug'] == 'dpt09']['indicator_value'].sum()), 2)
    d['stdm8'] = round((x[x['indicator_slug'] == 'dpt15']['indicator_value'].sum() + x[x['indicator_slug'] == 'dpt09']['indicator_value'].sum()) / (x[x['indicator_slug'] == 'tntfy']['indicator_value'].sum()), 2) 
        
    d['scheme'] = 'mgnrega'
    d['dist_slug'] = slugify(x.iloc[0]['district_name'])
    return pd.Series(d, index=['dist_slug', 'scheme', 'pdcpd', 'cesaf', 'aeaaw', 'ppcgt', 'sscjc', 'sstjc', 'sonsn', 'stwac', 'easeo',
                               'ntdm8', 'stdm8'])

In [5]:
data_tgt = data.groupby(['district_name']).apply(f).reset_index()

/home/abhinav/pyprojenv/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in double_scalars
  This is separate from the ipykernel package so we can avoid doing imports until
/home/abhinav/pyprojenv/lib/python3.6/site-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in double_scalars
  after removing the cwd from sys.path.

In [6]:
data_tgt

,district_name,dist_slug,scheme,pdcpd,cesaf,aeaaw,ppcgt,sscjc,sstjc,sonsn,stwac,easeo,ntdm8,stdm8
0,Bajali,bajali,mgnrega,20.55,NaN,63.76,86.77,2.51,3.62,93.87,0.0,92.64,780.0,0.01
1,Baksa,baksa,mgnrega,53.79,NaN,58.48,86.78,4.11,43.38,52.51,0.0,87.68,4305.0,0.05
2,Barpeta,barpeta,mgnrega,139.00,NaN,70.06,83.59,2.42,0.43,97.15,0.0,92.04,2853.0,0.01
3,Biswanath,biswanath,mgnrega,28.13,NaN,45.95,88.99,7.74,19.61,72.65,0.0,89.56,5939.0,0.05
4,Bongaigaon,bongaigaon,mgnrega,31.69,NaN,42.16,73.22,5.73,1.16,93.11,0.0,85.86,3408.0,0.03
5,Cachar,cachar,mgnrega,inf,NaN,33.18,78.23,6.24,1.20,92.56,0.0,88.35,11429.0,0.15
6,Charaideo,charaideo,mgnrega,31.06,NaN,48.36,94.32,1.88,2.54,95.58,0.0,83.93,75.0,0.00
7,Chirang,chirang,mgnrega,46.14,NaN,37.82,78.61,6.30,44.43,49.28,0.0,90.58,3545.0,0.05
8,Darrang,darrang,mgnrega,80.61,NaN,45.52,75.85,2.33,0.34,97.33,0.0,90.08,8010.0,0.04
9,Dhemaji,dhemaji,mgnrega,52.59,NaN,37.97,90.23,4.82,45.61,49.57,0.0,89.46,13899.0,0.07
10,Dhubri,dhubri,mgnrega,48.92,NaN,37.17,87.06,0.64,0.07,99.28,0.0,88.64,40152.0,0.20
11,Dibrugarh,dibrugarh,mgnrega,inf,NaN,35.70,90.60,3.31,10.63,86.07,0.0,84.00,917.0,0.01
12,Dima Hasao,dima-hasao,mgnrega,inf,NaN,41.90,67.00,5.39,77.13,17.48,0.0,79.57,418.0,0.05
13,Goalpara,goalpara,mgnrega,189.74,NaN,43.56,72.62,2.93,19.28,77.79,0.0,89.67,11253.0,0.09
14,Golaghat,golaghat,mgnrega,180.23,NaN,49.05,88.31,5.28,12.05,82.66,0.0,88.56,4613.0,0.03
15,Hailakandi,hailakandi,mgnrega,3.44,NaN,48.91,81.56,6.86,1.13,92.00,0.0,73.27,1203.0,0.02
16,Hojai,hojai,mgnrega,71.23,NaN,47.33,91.48,12.24,2.72,85.05,0.0,83.14,701.0,0.01
17,Jorhat,jorhat,mgnrega,178.75,NaN,58.10,90.14,6.12,7.34,86.54,0.0,81.85,4316.0,0.05
18,Kamrup,kamrup,mgnrega,920.73,NaN,45.60,88.28,5.93,9.60,84.47,0.0,86.43,12054.0,0.08
19,Kamrup (Metro),kamrup-metro,mgnrega,12.11,NaN,72.81,63.21,22.64,27.23,50.13,0.0,83.36,606.0,0.04
20,Karbi Anglong,karbi-anglong,mgnrega,inf,NaN,37.32,88.05,6.06,73.50,20.45,0.0,81.29,5797.0,0.09
21,Karimganj,karimganj,mgnrega,5.68,NaN,31.96,95.30,11.88,0.93,87.19,0.0,89.21,2262.0,0.02
22,Kokrajhar,kokrajhar,mgnrega,34.60,NaN,47.20,80.30,1.63,37.37,61.01,0.0,90.74,9749.0,0.04
23,Lakhimpur,lakhimpur,mgnrega,222.98,NaN,40.89,82.38,4.73,24.18,71.10,0.0,92.10,3304.0,0.02
24,Majuli,majuli,mgnrega,inf,NaN,65.40,41.98,11.27,46.30,42.43,0.0,85.13,3197.0,0.10
25,Morigaon,morigaon,mgnrega,28.57,NaN,50.78,83.13,9.71,10.64,79.65,0.0,88.68,7173.0,0.05
26,Nagaon,nagaon,mgnrega,9.12,NaN,59.75,90.22,4.50,2.64,92.87,0.0,90.58,7927.0,0.03
27,Nalbari,nalbari,mgnrega,inf,NaN,50.81,82.52,3.30,1.94,94.76,0.0,91.30,14479.0,0.08
28,Sivasagar,sivasagar,mgnrega,96.27,NaN,59.92,92.02,5.37,8.85,85.78,0.0,86.63,2055.0,0.02
29,Sonitpur,sonitpur,mgnrega,53.62,NaN,40.48,88.99,3.24,5.20,91.56,0.0,85.76,10898.0,0.12
30,South Salmara-Mankachar,south-salmara-mankachar,mgnrega,inf,NaN,47.21,72.33,1.11,0.61,98.28,0.0,82.67,17128.0,0.14
31,Tamulpur,tamulpur,mgnrega,inf,NaN,45.74,75.79,13.29,38.91,47.81,0.0,84.86,3104.0,0.07
32,Tinsukia,tinsukia,mgnrega,36.53,NaN,47.79,86.58,1.56,8.49,89.95,0.0,85.20,4572.0,0.04
33,Udalguri,udalguri,mgnrega,inf,NaN,53.11,90.00,4.20,39.43,56.37,0.0,86.85,4764.0,0.03
34,West Karbi Anglong,west-karbi-anglong,mgnrega,inf,NaN,41.41,94.27,2.88,72.47,24.65,0.0,77.82,1876.0,0.16

In [7]:
data.head()

,block_name,block_code,district_name,district_code,financial_year,scheme_name,indicator_report,date_of_update,indicator_name,indicator_slug,indicator_value,indicator_selected,indicator_unit
0,Tamulpur,1.0,Tamulpur,32.0,2023-2024,MGNREGA,Category Wise Household Workers,7-2023-09-34,No of jobcards applied for,no_slug,41853.0,no,--
1,Nagrijuli,2.0,Tamulpur,32.0,2023-2024,MGNREGA,Category Wise Household Workers,7-2023-09-34,No of jobcards applied for,No of jobcards applied for,25807.0,no,--
2,Goreswar,3.0,Tamulpur,32.0,2023-2024,MGNREGA,Category Wise Household Workers,7-2023-09-34,No of jobcards applied for,no_slug,56409.0,no,--
3,Kaliapani,1.0,Jorhat,18.0,2023-2024,MGNREGA,Category Wise Household Workers,7-2023-09-33,No of jobcards applied for,no_slug,19447.0,no,--
4,Jorhat East,2.0,Jorhat,18.0,2023-2024,MGNREGA,Category Wise Household Workers,7-2023-09-33,No of jobcards applied for,no_slug,21349.0,no,--

In [10]:
base_json = {}

for index, row in data.iterrows():
    
    # insert district
    if  slugify(row.district_name) not in base_json:
        base_json[slugify(row.district_name)] = {"distTitle": row.district_name, "depts": {"panchayat-and-rural-development": {"deptTitle": "Panchayat & Rural Development",
                    "schemes": {"mgnrega": {"schemeTitle": "Mahatma Gandhi National Rural Employment Guarantee Act (MGNREGA)",
                    "indicators": {slugify(row.indicator_name): {"indicatorTitle":row.indicator_name, "years": {row.financial_year: 
                        [{"blockName": row.block_name, "value": row.indicator_value}]
                    }}}}} }}}
    elif slugify(row.indicator_name) not in base_json[slugify(row.district_name)]['depts']['panchayat-and-rural-development']['schemes']['mgnrega']['indicators']:
        base_json[slugify(row.district_name)]['depts']['panchayat-and-rural-development']['schemes']['mgnrega']['indicators'][slugify(row.indicator_name)] = {
         "indicatorTitle":row.indicator_name, "years": {row.financial_year: [{"blockName": row.block_name, "value": row.indicator_value}]  }
        }
    elif slugify(row.financial_year) not in base_json[slugify(row.district_name)]['depts']['panchayat-and-rural-development']['schemes']['mgnrega']['indicators'][slugify(row.indicator_name)]["years"]:
        base_json[slugify(row.district_name)]['depts']['panchayat-and-rural-development']['schemes']['mgnrega']['indicators'][slugify(row.indicator_name)]["years"][slugify(row.financial_year)]= {
          [{"blockName": row.block_name, "value": row.indicator_value}]  
        }
    else:
        base_json[slugify(row.district_name)]['depts']['panchayat-and-rural-development']['schemes']['mgnrega']['indicators'][slugify(row.indicator_name)]["years"][slugify(row.financial_year)].append({"blockName": row.block_name, "value": row.indicator_value})
    if index > 5:
        break 
        
with open('scheme_explorer_1.json', 'w') as fp:
    json.dump(base_json, fp, indent=4)